log tnt_0\tnt_0.log; mxram 200; proc tnt_0\tnt_0.tnt; rs 0;
hold 1000;
ratchet: iter 200 upfactor 4 downfact 4;
ratchet:;
drift: iter 50;
drift:;
tfuse: rounds 5;
tfuse:;
mult 1;
ratchet;
drift;
tfuse;
bbreak;
tsave * tnt_0\tnt_0.tre;save;
quit;
